### ISSUE TITLE
Google Autofill bug

### ISSUE THREAD

**Issue by hotgen** [RobertWHurst/Keystrokes#50]
**Describe the bug**
When I select one of the options in Google Autofill, an exception occurs:

```
keystrokes.umd.cjs:1 Uncaught TypeError: Cannot read properties of undefined (reading 'toLowerCase')
    at g._handleKeyPress (keystrokes.umd.cjs:1:9512)
    at eval (keystrokes.umd.cjs:1:8962)
    at HTMLDocument.e (keystrokes.umd.cjs:1:1273)
_handleKeyPress @ keystrokes.umd.cjs:1
eval @ keystrokes.umd.cjs:1
e @ keystrokes.umd.cjs:1

keystrokes.umd.cjs:1 Uncaught TypeError: Cannot read properties of undefined (reading 'toLowerCase')
    at g._handleKeyRelease (keystrokes.umd.cjs:1:10240)
    at eval (keystrokes.umd.cjs:1:9020)
    at HTMLDocument.e (keystrokes.umd.cjs:1:1523)
```

**To Reproduce**
Here is the Codesandbox. You should have some Autofill options for "username" input:
https://codesandbox.io/p/sandbox/vibrant-curran-5zvtfw

**Expected behavior**
No errors.

**Comment by RobertWHurst** [comment]
Odd. Not sure why this is. If anyone has the time to debug it would be appricated.

**Comment by Paul2803k** [comment]
I have been having the same issue! I may try to take a look at some point next month :)

**Comment by MichaelBuessemeyer** [comment]
If anyone comes across this: 
Browsers can send keyup events with `key === undefined`. See https://stackoverflow.com/questions/45433810/event-key-is-undefined-in-mobile-browsers-for-keyup-keydown-and-keypress.
Thus, keystrokes should simply detect and ignore such events I think.

This is the same as https://github.com/RobertWHurst/Keystrokes/issues/64. #64 already suggests a fix (untested by me)
